apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-credential-helper
  namespace: kube-credential-helper
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    k8s-app: kube-credential-helper
  name: kube-credential-helper
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
      - serviceaccounts
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update
      - watch
  - apiGroups:
      - ""
    resources:
      - namespaces
    verbs:
      - list
      - get
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-credential-helper
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-credential-helper
subjects:
  - kind: ServiceAccount
    name: kube-credential-helper
    namespace: kube-credential-helper