#config.ini内容
#[docker]
#  url      = hub.docker.com
#  user     = cccfs
#  password = xxxxxx

#base64 encrypt config.ini
#cat config.ini |base64 -w 0

apiVersion: v1
data:
  config.ini: W2RvY2tlcl0KdXJsICAgICAgPSBodWIuZG9ja2VyLmNvbQp1c2VyICAgICA9IGNjY2ZzCnBhc3N3b3JkID0geHh4eHh4
kind: Secret
metadata:
  name: config
  namespace: kube-credential-helper
type: Opaque